$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:2
        },
        700:{
            items:3
        },
        1000:{
            items:4
        },
        1200:{
            items:6
        }
    
    }
})